spring:
  application:
    name: user-profile-service

service:
  keycloak:
    realm: zabardast
    profiles-url: "${KEYCLOCK_URL:http://localhost:8080}/auth/admin/realms/${KEYCLOCK_REALM:zabardast}"
  tasks:
    userprofilessync:
      fixedDelay: 180000
      batchSize: 1
