
server:
  port: 8888
  ssl:
    enabled: false
    client-auth: none
    #    protocol: TLS
    #    enabled-protocols: TLSv1.2
    key-store: classpath:keystore/server.jks
    key-alias: server
    key-store-type: JKS
    key-store-password: zabardast
    trust-store: classpath:keystore/server.jks
    trust-store-type: JKS
    trust-store-password: zabardast

spring:
  application:
    name: config-service
  profiles:
    active: native
  boot:
    admin:
      context-path: /admin
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        prefix: /config
        native:
          search-locations: 
          - 'classpath:/config'
          - 'classpath:/config/{application}'
          - 'classpath:/config/{application}/{profile}'
    # stream:
    #   kafka:
    #     binder:
    #       brokers: "${KAFKA_BROKERS:localhost:9092}"
    #       zkNodes: "${ZOOKEEPER_NODES:localhost:2181}"

