server:
  port: ${GATEWAY_PORT:9000}
  ssl:
    enabled: false
    key-alias: eagleeye
    key-store-type: PKCS12
    key-store: classpath:keystore/eagleeye.p12
    key-store-password: changeit

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env,health,metrics,gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9001}/eureka

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      x-forwarded:
        for.enabled: true
        host.enabled: true
        port.enabled: true
        proto.enabled: true
        prefix.enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: license
          uri: lb://blog-service
          predicates:
            - Path=/blog/**
          filters:
            - TokenRelay=
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
        - id: organization
          uri: lb://bookmarks-service
          predicates:
            - Path=/bookmarks/**
          filters:
            - TokenRelay=
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns:
              - https://localhost:*
              - http://localhost:*
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: "${KEYCLOCK_URL:http://localhost:8080}/auth/realms/${KEYCLOCK_REALM:zabardast}/protocol/openid-connect/token"
            authorization-uri: "${KEYCLOCK_URL:http://localhost:8080}/auth/realms/${KEYCLOCK_REALM:zabardast}/protocol/openid-connect/auth"
            userinfo-uri: "${KEYCLOCK_URL:http://localhost:8080}/auth/realms/${KEYCLOCK_REALM:zabardast}/protocol/openid-connect/userinfo"
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: zabardast-service-client
            client-secret: "c2ac53d1-1179-4fca-bd6e-c421d1a37e59"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/zabardast-service-client"

