logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:userprofiles;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS userprofiles"
    username: sa
    password: sa
