spring:
  application:
    name: eureka-service
  config:
    import: "configserver:${CONFIG_URI:http://localhost:8888/config}"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: ${CONFIG_RETRY_INITIAL_INTERVAL:3000}
        multiplier: ${CONFIG_RETRY_MULTIPLIER:1.2}
        max-interval: ${CONFIG_RETRY_MAX_INTERVAL:15000}
        max-attempts: ${CONFIG_RETRY_MAX_ATTEMPTS:15}

server:
  port: 9001
  ssl:
    enabled: false
    client-auth: none
    #    protocol: TLS
    #    enabled-protocols: TLSv1.2
    key-store: classpath:keystore/server.jks
    key-alias: server
    key-store-type: JKS
    key-store-password: zabardast
    trust-store: classpath:keystore/server.jks
    trust-store-type: JKS
    trust-store-password: zabardast
