server:
  port: ${BLOG_SERVICE_PORT:9081}
  ssl:
    enabled: ${BLOG_SERVICE_SSL_ENABLED:false}
    client-auth: ${BLOG_SERVICE_SSL_CLIENT_AUTH:none}
    #    protocol: TLS
    #    enabled-protocols: TLSv1.2
    key-store: classpath:keystore/server.jks
    key-alias: server
    key-store-type: JKS
    key-store-password: zabardast
    trust-store: classpath:keystore/server.jks
    trust-store-type: JKS
    trust-store-password: zabardast

spring:
  cloud:
    config:
      enabled: false
    stream:
      source: producer
      kafka:
        binder:
          brokers: "${KAFKA_BROKERS:localhost:9094}"
          zkNodes: "${ZOOKEEPER_NODES:localhost:2181}"
      bindings:
        producer-out-0:
          destination: domain-events
        consumer-in-0:
          destination: domain-events
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:blog;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS blog"
    username: sa
    password: sa
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${KEYCLOCK_URL:http://localhost:8080}/auth/realms/${KEYCLOCK_REALM:zabardast}/protocol/openid-connect/certs"
eureka:
  client:
    enabled: false
