spring:
  application:
    name: gateway
  config:
    import: "configserver:${CONFIG_URI:http://localhost:8888/config}"
    fail-fast: true
    retry:
      initial-interval: 3000
      multiplier: 1.3
      max-interval: 10000
      max-attempts: 1000
