version: "3.7"

networks:
  default:
    name: zabardast.net
    ipam:
      config:
      - subnet: 172.33.0.0/16

volumes:
  elasticsearch_data:
    driver: local

services:
  elasticsearch:
    image: elasticsearch:1.5.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      LOGSPOUT: 'ignorex'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      ES_HOSTS: 'http://elasticsearch:9200'
      ES_INDEX: 'logstash-*'
      STORAGE_TYPE: elasticsearch
      LOGSPOUT: 'ignorex'

  kibana:
    image: kibana:4.1.2
    links:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      LOGSPOUT: 'ignorex'
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:2.1.1
    command: 'logstash -e "input { udp { port => 5000 } } output { elasticsearch { hosts => elasticsearch } }"'
    environment:
      STDOUT: 'true'
      LOGSPOUT: 'ignorex'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana

  logspout:
    image: gliderlabs/logspout:v3
    command: 'udp://logstash:5000'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - elasticsearch
      - logstash
      - kibana
