version: "3.7"

networks:
  default:
    name: zabardast.net
    ipam:
      config:
      - subnet: 172.33.0.0/16

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_conf:
    driver: local

services:
  # Infrastructure
  localdns:
    image: defreitas/dns-proxy-server
    hostname: dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - MG_LOG_LEVEL=ERROR

  database:
    image: zabardast/postgres
    hostname: database
    build:
      context: ../infra/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: on-failure:30
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    restart: on-failure:30
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9094,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9094,EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_RETENTION_HOURS: 240
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 6000000
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    restart: on-failure:30
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'zookeeper'
    volumes:
      - zookeeper_data:/opt/zookeeper-3.4.13/data
      - zookeeper_conf:/opt/zookeeper-3.4.13/conf

  keycloak:
    image: zabardast/keycloak
    hostname: keycloak
    build:
      context: ../infra/keycloak
      dockerfile: Dockerfile
      args:
        user: service
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: on-failure:30
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_SCHEMA: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - database

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    restart: "no"
    ports:
      - "8081:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9094
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      LOGSPOUT: 'ignore'
    depends_on:
      - "kafka"

